'use strict';
const LEVELS=window.LEVELS||[];
const STORY=window.LATCHLINGS_STORY||null;
const CHAPTERS=STORY?STORY.chapters:[
 {name:'First Snaps',theme:'Sunpetal Meadows',desc:'Edges, rocks, and clean magnetic routes. The meadow starts gentle, then grows into long setup puzzles.',tip:'Use the whole board. Sometimes the useful stopping point is several snaps away from the nest.',color:'#b9dcf4'},
 {name:'Clever Stops',theme:'Lanternwood Grove',desc:'Other Latchlings become movable stoppers in a lantern-lit forest of increasingly tangled routes.',tip:'A Latchling can be more valuable as a temporary wall than as the next piece you finish.',color:'#294e62'},
 {name:'Magnetic Anchors',theme:'Lodestone Caverns',desc:'Anchors create precise stops inside crystal caverns while earlier stopper logic remains in play.',tip:'Treat anchors as movable-route geometry: landing on one can set up the next two or three snaps.',color:'#25354d'},
 {name:'Suit Gates',theme:'Masquerade Keep',desc:'Black suit marks decide which Latchling can cross each gate inside the moonlit keep.',tip:'If a route looks blocked, ask whether the wrong Latchling is approaching the gate.',color:'#403052'},
 {name:'Color Gates',theme:'Prism Gardens',desc:'Body color joins suit logic in a luminous garden where identity matters as much as position.',tip:'Separate the two clues: body color answers one gate, black suit answers another.',color:'#82cbd0'},
 {name:'Rails and Turns',theme:'Copperline Junction',desc:'Directional rails and turners reshape continuous snaps across a warm copper transit hub.',tip:'A turner changes direction without ending the move. Trace the entire snap before pressing.',color:'#9a6748'},
 {name:'Switchworks',theme:'Stormswitch Foundry',desc:'Switches, doors, rails, and identity gates combine inside an electric storm foundry.',tip:'A switch is about timing, not just activation. Opening a door can also remove a useful stopping wall.',color:'#283a4c'},
 {name:'Master Circuit',theme:'Aurora Crown',desc:'Every mechanic is active beneath the aurora. These are the campaign’s longest and most layered routes.',tip:'Read the board as a sequence of future board states, not as a single move.',color:'#172b52'}
 ];
const COLORS={coral:'#ef5f66',blue:'#4c8ff4',mint:'#66bd72',gold:'#f6b737',lavender:'#9a72df'};
const LIGHT={coral:'#ff9297',blue:'#79aff9',mint:'#94dc98',gold:'#ffd06a',lavender:'#c3a0f1'};
const DARK={coral:'#c33d49',blue:'#2e69c8',mint:'#469852',gold:'#d18c16',lavender:'#724fbd'};
const DIRV={U:[-1,0],D:[1,0],L:[0,-1],R:[0,1]}; const CW={U:'R',R:'D',D:'L',L:'U'},CCW={U:'L',L:'D',D:'R',R:'U'};
let currentLevel=1,chapterView=1,rangeView=0,selected=0,movesUsed=0,doorMask=0,positions=[],animating=false,hintStep=0;
const PROGRESS_KEY='latchlings_campaign400_progress_v1';
let progress=loadProgress();
function loadProgress(){try{const x=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');return {unlocked:Math.max(1,Math.min(400,x.unlocked||1)),stars:x.stars||{}}}catch(e){return {unlocked:1,stars:{}}}}
function saveProgress(){localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress));updateHome()}
function showError(e){const d=document.getElementById('debug');d.style.display='block';d.dataset.playerSafe='true';d.textContent='Something went wrong. Return to Level Select and try again.'}
window.addEventListener('error',e=>showError(e.error||e.message));window.addEventListener('unhandledrejection',e=>showError(e.reason));
let activeScreenTransition=null;function screen(id){const next=document.getElementById(id),current=document.querySelector('.screen.active');if(!next)return;if(current===next){document.body.dataset.screen=id;if(id==='home')setTimeout(()=>updateHome(true),0);return}const swap=()=>{document.body.dataset.screen=id;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));next.classList.add('active');if(id==='home')setTimeout(()=>updateHome(true),0)};const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,canSwipe=!!current&&!reduced&&typeof document.startViewTransition==='function';if(!canSwipe){swap();return}try{if(activeScreenTransition&&typeof activeScreenTransition.skipTransition==='function')activeScreenTransition.skipTransition();const vt=document.startViewTransition(swap);activeScreenTransition=vt;if(window.LatchlingsSFX&&window.LatchlingsSFX.screenSwipe)window.LatchlingsSFX.screenSwipe();vt.finished.finally(()=>{if(activeScreenTransition===vt)activeScreenTransition=null})}catch(_){activeScreenTransition=null;swap()}}
function icon(name){const paths={
 back:'<path d="M15 5 8 12l7 7"/><path d="M8 12h10"/>',pause:'<path d="M9 5v14M15 5v14"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.12-1.28l2-1.55-2-3.46-2.45 1a7 7 0 0 0-2.2-1.28L13.9 3h-4l-.36 2.43a7 7 0 0 0-2.2 1.28l-2.45-1-2 3.46 2 1.55A7 7 0 0 0 4.8 12c0 .44.04.87.12 1.28l-2 1.55 2 3.46 2.45-1a7 7 0 0 0 2.2 1.28L9.9 21h4l.36-2.43a7 7 0 0 0 2.2-1.28l2.45 1 2-3.46-2-1.55c.08-.41.12-.84.12-1.28Z"/>',reset:'<path d="M4 7v5h5"/><path d="M5.6 16a7 7 0 1 0 .2-8.2L4 10"/>',hint:'<path d="M9 18h6M10 21h4"/><path d="M8.4 14.3A6 6 0 1 1 15.6 14.3c-1.1.8-1.6 1.5-1.6 2.7h-4c0-1.2-.5-1.9-1.6-2.7Z"/>',up:'<path d="M5 15 12 8l7 7"/>',down:'<path d="m5 9 7 7 7-7"/>',left:'<path d="m15 5-7 7 7 7"/>',right:'<path d="m9 5 7 7-7 7"/>',anchor:'<circle cx="12" cy="5" r="2"/><path d="M12 7v11M7 10h10M5 15c1 4 4 6 7 6s6-2 7-6M5 15l-2 1M19 15l2 1"/>'};return `<svg class="icon" viewBox="0 0 24 24">${paths[name]||''}</svg>`}
function suitSvg(s){
 if(s==='heart')return '<svg viewBox="0 0 100 100"><path d="M50 86C39 74 13 58 13 34c0-14 10-23 23-23 8 0 14 4 18 10 4-6 10-10 18-10 13 0 23 9 23 23 0 24-26 40-45 52Z"/></svg>';
 if(s==='diamond')return '<svg viewBox="0 0 100 100"><path d="M50 7 88 50 50 93 12 50Z"/></svg>';
 if(s==='club')return '<svg viewBox="0 0 100 100"><path d="M50 12a19 19 0 0 1 12 34 20 20 0 1 1 9 37c-9 0-15-5-18-11 1 10 5 16 12 21H35c7-5 11-11 12-21-3 6-9 11-18 11a20 20 0 1 1 9-37A19 19 0 0 1 50 12Z"/></svg>';
 if(s==='spade')return '<svg viewBox="0 0 100 100"><path d="M50 8C43 22 14 36 14 60c0 13 10 23 23 23 8 0 13-4 16-10-1 9-5 15-12 20h18c-7-5-11-11-12-20 3 6 8 10 16 10 13 0 23-10 23-23C86 36 57 22 50 8Z"/></svg>';
 return '<svg viewBox="0 0 100 100"><path d="m50 7 13 27 30 4-22 21 6 30-27-14-27 14 6-30L7 38l30-4Z"/></svg>';
}
function gateColor(color){return COLORS[color]||'#4c8ff4'}
function expressionFor(levelId,pi,piece){const allowed=['happy','surprised','angry','smug','sleepy','curious','determined'];const authored=piece&&piece.expression;return allowed.includes(authored)?authored:allowed[(levelId*7+pi*11)%allowed.length]}
function applyTheme(ch){ch=Math.max(1,Math.min(8,ch));const app=document.getElementById('app');for(let i=1;i<=8;i++)app.classList.remove('theme-ch'+i);app.classList.add('theme-ch'+ch);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',CHAPTERS[ch-1].color)}
function clockwiseAvailable(){const lev=LEVELS[currentLevel-1],mid=(lev.size-1)/2;return positions.map((p,i)=>p?{i,p,a:(Math.atan2(p[1]-mid,-(p[0]-mid))+Math.PI*2)%(Math.PI*2)}:null).filter(Boolean).sort((a,b)=>a.a-b.a||a.i-b.i).map(x=>x.i)}
function cycleLatchling(){if(animating)return;const order=clockwiseAvailable();if(order.length<2)return;const at=order.indexOf(selected);selected=order[(at<0?0:at+1)%order.length];renderPieces(LEVELS[currentLevel-1]);if(window.LatchlingsSFX)window.LatchlingsSFX.cycleLatchling()}
function nearestLatchling(origin){let best=-1,bestD=Infinity;positions.forEach((p,i)=>{if(!p)return;const d=(p[0]-origin[0])**2+(p[1]-origin[1])**2;if(d<bestD||(d===bestD&&i<best)){bestD=d;best=i}});return best}
function starSvg(on,cls=''){return `<span class="win-star ${on?'on':''} ${cls}"><svg viewBox="0 0 100 100" aria-hidden="true"><path class="core" d="M50 8 62 35 92 38 69 58 75 88 50 72 25 88 31 58 8 38 38 35 Z"/><path class="shine" d="M50 17 58 35 78 37 63 50 67 68 50 58 33 68 37 50 22 37 42 35 Z"/></svg></span>`}
function updateHome(replay=false){const total=Object.values(progress.stars).reduce((a,b)=>a+(+b||0),0),legacy=document.getElementById('homeStars');if(legacy)legacy.textContent=total;const frame=document.getElementById('homeTitleFrame'),stage=STORY?STORY.completedChapters(progress):0;if(frame&&frame.contentWindow)frame.contentWindow.postMessage({source:'latchlings-game',type:'home-state',stars:total,stage,replay:!!replay},location.origin)}
function renderChapter(){chapterView=Math.max(1,Math.min(8,chapterView));rangeView=Math.max(0,Math.min(4,rangeView));applyTheme(chapterView);const ch=CHAPTERS[chapterView-1],chapterStart=(chapterView-1)*50+1;document.getElementById('chapterHead').innerHTML=`<div class="chapter-badge">${chapterView}</div><div><div class="theme-kicker">${ch.theme}</div><h2>Chapter ${chapterView}: ${ch.name}</h2><p>${ch.desc}</p><p class="chapter-mechanic"><strong>Route language:</strong> ${ch.mechanic||''}</p><p class="chapter-opening">${ch.opening||''}</p></div>`;document.getElementById('chapterNav').innerHTML=CHAPTERS.map((c,i)=>`<button class="chapter-chip ${i+1===chapterView?'active':''}" data-ch="${i+1}">${i+1}. ${c.name}</button>`).join('');document.querySelectorAll('.chapter-chip').forEach(b=>b.onclick=()=>{chapterView=+b.dataset.ch;const local=progress.unlocked-(chapterView-1)*50;rangeView=local>0?Math.min(4,Math.floor((local-1)/10)):0;renderChapter()});document.getElementById('rangeNav').innerHTML=Array.from({length:5},(_,i)=>`<button class="range-chip ${i===rangeView?'active':''}" data-range="${i}">${i*10+1}–${i*10+10}</button>`).join('');document.querySelectorAll('.range-chip').forEach(b=>b.onclick=()=>{rangeView=+b.dataset.range;renderChapter()});const start=chapterStart+rangeView*10;document.getElementById('levelGrid').innerHTML=Array.from({length:10},(_,j)=>{const L=start+j,locked=L>progress.unlocked,done=(progress.stars[L]||0)>0,stars=progress.stars[L]||0;return `<button class="level-node ${locked?'locked':''} ${done?'done':''} ${L===progress.unlocked?'current':''}" data-level="${L}" ${locked?'disabled':''}><span class="level-local">${L-chapterStart+1}</span><span class="level-global">${L}</span><span class="stars">${[1,2,3].map(s=>`<i class="star-dot ${s<=stars?'on':''}"></i>`).join('')}</span></button>`}).join('');document.querySelectorAll('.level-node:not(.locked)').forEach(b=>b.onclick=()=>startLevel(+b.dataset.level))}
function startLevel(L){currentLevel=Math.max(1,Math.min(400,L));const lev=LEVELS[currentLevel-1];if(!lev){showError('Missing level '+currentLevel);return}chapterView=Math.ceil(currentLevel/50);rangeView=Math.floor(((currentLevel-1)%50)/10);applyTheme(chapterView);positions=lev.pieces.map(p=>p.pos.slice());doorMask=0;movesUsed=0;selected=0;hintStep=0;animating=false;screen('game');renderGame(true);const enterStory=()=>{if(window.LatchlingsStoryTheme)window.LatchlingsStoryTheme.enterLevel(currentLevel)},enterCinematicOrStory=()=>{if(window.LatchlingsCinematics&&window.LatchlingsCinematics.maybeShowBeforeLevel(currentLevel,progress.unlocked,enterStory))return;enterStory()};if(activeScreenTransition&&activeScreenTransition.finished)activeScreenTransition.finished.then(enterCinematicOrStory).catch(enterCinematicOrStory);else enterCinematicOrStory()}
function renderGame(full=false){const lev=LEVELS[currentLevel-1];applyTheme(Math.ceil(currentLevel/50));const storyMeta=STORY?STORY.levelMeta(currentLevel):null;document.getElementById('levelTitle').textContent='Level '+currentLevel;document.getElementById('movesLeft').textContent=Math.max(0,lev.moveLimit-movesUsed);const note=document.getElementById('mechanicNote');note.classList.remove('story-note');note.classList.add('mechanic-chip');note.innerHTML=`<span class="mechanic-chip-label">Route tip</span><span class="mechanic-chip-copy">${chapterNote(currentLevel)}</span>`;if(window.LatchlingsStoryTheme)window.LatchlingsStoryTheme.decorateLevel(currentLevel,storyMeta);const board=document.getElementById('board');board.style.setProperty('--n',lev.size);if(full){board.querySelectorAll('.cell').forEach(x=>x.remove());for(let r=0;r<lev.size;r++)for(let c=0;c<lev.size;c++){const cell=document.createElement('div');cell.className='cell';cell.dataset.r=r;cell.dataset.c=c;board.insertBefore(cell,document.getElementById('pieceLayer'));decorateCell(cell,lev,r,c)}}renderPieces(lev)}
function chapterNote(L){const k=(L-1)%50+1,ch=Math.ceil(L/50),c=CHAPTERS[ch-1];if(k<=2)return (c.mechanic?c.mechanic+'. ':'')+c.tip;if(ch===1&&k<=5)return 'A snap continues until something stops it. Use the board edge and rocks to line up the nest.';if(ch===2&&k<=5)return 'Other Latchlings are movable walls. Park one where another needs to stop.';if(ch===3&&k<=5)return 'Anchors create exact stopping points without needing a wall behind them.';if(ch===4&&k<=5)return 'Read the black suit mark before committing to a gate route.';if(ch===5&&k<=5)return 'Body color and suit are separate clues now. Check both before you snap.';if(ch===6&&k<=5)return 'Rails restrict entry; turners bend one continuous snap without spending another move.';if(ch===7&&k<=5)return 'Switch order matters. Open the route you need before committing a Latchling to it.';if(ch===8&&k<=5)return 'Everything is live. Read the whole circuit before your first move.';if(k>=46)return 'Expert board: expect setup moves, temporary blockers, and routes that only make sense several snaps ahead.';return c.tip}
function findAt(arr,r,c){return (arr||[]).find(x=>x[0]===r&&x[1]===c)}
function decorateCell(cell,lev,r,c){const rock=findAt(lev.rocks,r,c);if(rock){cell.innerHTML='<div class="rock"></div>';return}const nestI=lev.nests.findIndex(n=>n[0]===r&&n[1]===c);if(nestI>=0){const p=lev.pieces[nestI];cell.innerHTML=`<div class="nest" style="--piece-color:${COLORS[p.color]}">${suitSvg(p.suit)}</div>`;return}if(findAt(lev.anchors,r,c))cell.innerHTML+='<div class="anchor">'+icon('anchor')+'</div>';const sg=findAt(lev.suitGates,r,c);if(sg)cell.innerHTML+=`<div class="gate suit">${suitSvg(sg[2])}</div>`;const cg=findAt(lev.colorGates,r,c);if(cg)cell.innerHTML+=`<div class="gate color" style="--gate-color:${gateColor(cg[2])}"><span style="width:42%;height:42%;border-radius:50%;background:${gateColor(cg[2])};box-shadow:inset 0 0 0 4px rgba(255,255,255,.55)"></span></div>`;const rail=findAt(lev.rails,r,c);if(rail)cell.innerHTML+=`<div class="rail">${dirSvg(rail[2])}</div>`;const turn=findAt(lev.turners,r,c);if(turn)cell.innerHTML+=`<div class="turner">${turnSvg(turn[2])}</div>`;const sw=findAt(lev.switches,r,c);if(sw)cell.innerHTML+='<div class="switch-tile"></div>';const dr=findAt(lev.doors,r,c);if(dr)cell.innerHTML+=`<div class="door-tile ${(doorMask&(1<<dr[2]))?'open':''}"><div class="door-bars"></div></div>`}
function dirSvg(d){const rot={U:0,R:90,D:180,L:270}[d];return `<svg viewBox="0 0 24 24" style="transform:rotate(${rot}deg)"><path d="M12 19V5M6 11l6-6 6 6"/></svg>`}function turnSvg(t){return `<svg viewBox="0 0 24 24" ${t==='CCW'?'style="transform:scaleX(-1)"':''}><path d="M5 17h6a7 7 0 0 0 7-7V6"/><path d="m14 9 4-4 4 4"/></svg>`}
function renderPieces(lev){const layer=document.getElementById('pieceLayer');layer.innerHTML='';positions.forEach((pos,i)=>{if(!pos)return;const p=lev.pieces[i],el=document.createElement('button');el.className=`latchling expr-${expressionFor(currentLevel,i,p)} ${i===selected?'selected':''}`;el.dataset.pi=i;el.style.setProperty('--n',lev.size);el.style.setProperty('--piece-color',COLORS[p.color]);el.style.setProperty('--light',LIGHT[p.color]);el.style.setProperty('--dark',DARK[p.color]);const blinkDuration=(3.35+((currentLevel*17+i*29)%37)/10).toFixed(2)+'s',blinkDelay=(-((currentLevel*23+i*41)%59)/10).toFixed(2)+'s';el.style.setProperty('--blink-duration',blinkDuration);el.style.setProperty('--blink-delay',blinkDelay);el.style.setProperty('--idle-delay',(-((currentLevel*11+i*7)%23)/10).toFixed(2)+'s');placePiece(el,pos[0],pos[1],lev.size,false);el.innerHTML=`<span class="suit-mark">${suitSvg(p.suit)}</span><span class="face"><span class="eyes"><i class="eye"></i><i class="eye"></i></span><i class="mouth"></i></span>`;el.onclick=()=>{if(animating||selected===i)return;selected=i;renderPieces(lev);if(window.LatchlingsSFX)window.LatchlingsSFX.selectLatchling()};layer.appendChild(el)})}
