'use strict';
const CHAPTERS=[
 {name:'First Snaps',desc:'Learn full-distance movement, corners, rock stops, and your first piece-order setups.'},
 {name:'Clever Stops',desc:'Other Latchlings are part of the board. Park them where you need a stopper.'},
 {name:'Magnetic Anchors',desc:'Anchors stop a moving Latchling exactly on their tile.'},
 {name:'Suit Gates',desc:'A suit gate only allows a Latchling carrying the matching black suit mark.'},
 {name:'Color Gates',desc:'Color gates care about body color. Now color and suit are separate information.'},
 {name:'Rails and Turns',desc:'One-way rails restrict entry direction; turners bend a snap while it stays in motion.'},
 {name:'Switchworks',desc:'Pressure switches toggle linked doors. Route order matters.'},
 {name:'Master Circuit',desc:'Everything combines. Use position, identity, gates, rails, switches, and other Latchlings.'}
];
const COLORS={coral:'#ef5f66',blue:'#4c8ff4',mint:'#66bd72',gold:'#f6b737',lavender:'#9a72df'};
const LIGHT={coral:'#ff9297',blue:'#79aff9',mint:'#94dc98',gold:'#ffd06a',lavender:'#c3a0f1'};
const DARK={coral:'#c33d49',blue:'#2e69c8',mint:'#469852',gold:'#d18c16',lavender:'#724fbd'};
const DIRV={U:[-1,0],D:[1,0],L:[0,-1],R:[0,1]}; const CW={U:'R',R:'D',D:'L',L:'U'},CCW={U:'L',L:'D',D:'R',R:'U'};
let currentLevel=1,chapterView=1,selected=0,movesUsed=0,doorMask=0,positions=[],animating=false,hintStep=0;
let progress=loadProgress();
function loadProgress(){try{const x=JSON.parse(localStorage.getItem('latchlings_rebuild_progress')||'{}');return {unlocked:Math.max(1,Math.min(80,x.unlocked||1)),stars:x.stars||{}}}catch(e){return {unlocked:1,stars:{}}}}
function saveProgress(){localStorage.setItem('latchlings_rebuild_progress',JSON.stringify(progress));updateHome()}
function showError(e){const d=document.getElementById('debug');d.style.display='block';d.textContent='Prototype error: '+(e&&e.stack?e.stack:e)}
window.addEventListener('error',e=>showError(e.error||e.message));window.addEventListener('unhandledrejection',e=>showError(e.reason));
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active')}
function icon(name){const paths={
 back:'<path d="M15 5 8 12l7 7"/><path d="M8 12h10"/>',pause:'<path d="M9 5v14M15 5v14"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.12-1.28l2-1.55-2-3.46-2.45 1a7 7 0 0 0-2.2-1.28L13.9 3h-4l-.36 2.43a7 7 0 0 0-2.2 1.28l-2.45-1-2 3.46 2 1.55A7 7 0 0 0 4.8 12c0 .44.04.87.12 1.28l-2 1.55 2 3.46 2.45-1a7 7 0 0 0 2.2 1.28L9.9 21h4l.36-2.43a7 7 0 0 0 2.2-1.28l2.45 1 2-3.46-2-1.55c.08-.41.12-.84.12-1.28Z"/>',reset:'<path d="M4 7v5h5"/><path d="M5.6 16a7 7 0 1 0 .2-8.2L4 10"/>',hint:'<path d="M9 18h6M10 21h4"/><path d="M8.4 14.3A6 6 0 1 1 15.6 14.3c-1.1.8-1.6 1.5-1.6 2.7h-4c0-1.2-.5-1.9-1.6-2.7Z"/>',up:'<path d="M5 15 12 8l7 7"/>',down:'<path d="m5 9 7 7 7-7"/>',left:'<path d="m15 5-7 7 7 7"/>',right:'<path d="m9 5 7 7-7 7"/>',anchor:'<circle cx="12" cy="5" r="2"/><path d="M12 7v11M7 10h10M5 15c1 4 4 6 7 6s6-2 7-6M5 15l-2 1M19 15l2 1"/>'};return `<svg class="icon" viewBox="0 0 24 24">${paths[name]||''}</svg>`}
function suitSvg(s){
 if(s==='heart')return '<svg viewBox="0 0 100 100"><path d="M50 86C39 74 13 58 13 34c0-14 10-23 23-23 8 0 14 4 18 10 4-6 10-10 18-10 13 0 23 9 23 23 0 24-26 40-45 52Z"/></svg>';
 if(s==='diamond')return '<svg viewBox="0 0 100 100"><path d="M50 7 88 50 50 93 12 50Z"/></svg>';
 if(s==='club')return '<svg viewBox="0 0 100 100"><path d="M50 12a19 19 0 0 1 12 34 20 20 0 1 1 9 37c-9 0-15-5-18-11 1 10 5 16 12 21H35c7-5 11-11 12-21-3 6-9 11-18 11a20 20 0 1 1 9-37A19 19 0 0 1 50 12Z"/></svg>';
 if(s==='spade')return '<svg viewBox="0 0 100 100"><path d="M50 8C43 22 14 36 14 60c0 13 10 23 23 23 8 0 13-4 16-10-1 9-5 15-12 20h18c-7-5-11-11-12-20 3 6 8 10 16 10 13 0 23-10 23-23C86 36 57 22 50 8Z"/></svg>';
 return '<svg viewBox="0 0 100 100"><path d="m50 7 13 27 30 4-22 21 6 30-27-14-27 14 6-30L7 38l30-4Z"/></svg>';
}
function gateColor(color){return COLORS[color]||'#4c8ff4'}
function expressionFor(levelId,pi,piece){const allowed=['happy','surprised','angry','smug','sleepy','curious','determined'];const authored=piece&&piece.expression;return allowed.includes(authored)?authored:allowed[(levelId*7+pi*11)%allowed.length]}
function updateHome(){const total=Object.values(progress.stars).reduce((a,b)=>a+(+b||0),0);document.getElementById('homeStars').textContent=total}
function renderChapter(){const ch=CHAPTERS[chapterView-1];document.getElementById('chapterHead').innerHTML=`<div class="chapter-badge">${chapterView}</div><div><h2>Chapter ${chapterView}: ${ch.name}</h2><p>${ch.desc}</p></div>`;document.getElementById('chapterNav').innerHTML=CHAPTERS.map((c,i)=>`<button class="chapter-chip ${i+1===chapterView?'active':''}" data-ch="${i+1}">${i+1}. ${c.name}</button>`).join('');document.querySelectorAll('.chapter-chip').forEach(b=>b.onclick=()=>{chapterView=+b.dataset.ch;renderChapter()});const start=(chapterView-1)*10+1;document.getElementById('levelGrid').innerHTML=Array.from({length:10},(_,j)=>{const L=start+j,locked=L>progress.unlocked,done=progress.stars[L]>0,stars=progress.stars[L]||0;return `<button class="level-node ${locked?'locked':''} ${done?'done':''} ${L===progress.unlocked?'current':''}" data-level="${L}" ${locked?'disabled':''}>${L}<span class="stars">${[1,2,3].map(s=>`<i class="star-dot ${s<=stars?'on':''}"></i>`).join('')}</span></button>`}).join('');document.querySelectorAll('.level-node:not(.locked)').forEach(b=>b.onclick=()=>startLevel(+b.dataset.level))}
function startLevel(L){currentLevel=Math.max(1,Math.min(80,L));const lev=LEVELS[currentLevel-1];positions=lev.pieces.map(p=>p.pos.slice());doorMask=0;movesUsed=0;selected=0;hintStep=0;animating=false;screen('game');renderGame(true)}
function renderGame(full=false){const lev=LEVELS[currentLevel-1];document.getElementById('levelTitle').textContent='Level '+currentLevel;document.getElementById('movesLeft').textContent=Math.max(0,lev.moveLimit-movesUsed);document.getElementById('mechanicNote').textContent=chapterNote(currentLevel);const board=document.getElementById('board');board.style.setProperty('--n',lev.size);if(full){board.querySelectorAll('.cell').forEach(x=>x.remove());for(let r=0;r<lev.size;r++)for(let c=0;c<lev.size;c++){const cell=document.createElement('div');cell.className='cell';cell.dataset.r=r;cell.dataset.c=c;board.insertBefore(cell,document.getElementById('pieceLayer'));decorateCell(cell,lev,r,c)}}renderPieces(lev)}
function chapterNote(L){const k=(L-1)%10+1,ch=Math.ceil(L/10);if(k===1)return CHAPTERS[ch-1].desc;if(ch===1&&L<=3)return 'A snap continues until something stops it. Matching nests pull their Latchling in.';if(ch===1&&L<=5)return 'Use edges and rocks to create the stopping point you need.';if(ch===1)return 'Order matters now. A Latchling can temporarily become another Latchling’s stopper.';if(ch===2)return 'Try parking one Latchling where another needs a stopper.';return CHAPTERS[ch-1].name+' puzzle.'}
function findAt(arr,r,c){return (arr||[]).find(x=>x[0]===r&&x[1]===c)}
function decorateCell(cell,lev,r,c){const rock=findAt(lev.rocks,r,c);if(rock){cell.innerHTML='<div class="rock"></div>';return}const nestI=lev.nests.findIndex(n=>n[0]===r&&n[1]===c);if(nestI>=0){const p=lev.pieces[nestI];cell.innerHTML+=`<div class="nest" style="--piece-color:${COLORS[p.color]}">${suitSvg(p.suit)}</div>`}if(findAt(lev.anchors,r,c))cell.innerHTML+='<div class="anchor">'+icon('anchor')+'</div>';const sg=findAt(lev.suitGates,r,c);if(sg)cell.innerHTML+=`<div class="gate suit">${suitSvg(sg[2])}</div>`;const cg=findAt(lev.colorGates,r,c);if(cg)cell.innerHTML+=`<div class="gate color" style="--gate-color:${gateColor(cg[2])}"><span style="width:42%;height:42%;border-radius:50%;background:${gateColor(cg[2])};box-shadow:inset 0 0 0 4px rgba(255,255,255,.55)"></span></div>`;const rail=findAt(lev.rails,r,c);if(rail)cell.innerHTML+=`<div class="rail">${dirSvg(rail[2])}</div>`;const turn=findAt(lev.turners,r,c);if(turn)cell.innerHTML+=`<div class="turner">${turnSvg(turn[2])}</div>`;const sw=findAt(lev.switches,r,c);if(sw)cell.innerHTML+='<div class="switch-tile"></div>';const dr=findAt(lev.doors,r,c);if(dr)cell.innerHTML+=`<div class="door-tile ${(doorMask&(1<<dr[2]))?'open':''}"><div class="door-bars"></div></div>`}
function dirSvg(d){const rot={U:0,R:90,D:180,L:270}[d];return `<svg viewBox="0 0 24 24" style="transform:rotate(${rot}deg)"><path d="M12 19V5M6 11l6-6 6 6"/></svg>`}function turnSvg(t){return `<svg viewBox="0 0 24 24" ${t==='CCW'?'style="transform:scaleX(-1)"':''}><path d="M5 17h6a7 7 0 0 0 7-7V6"/><path d="m14 9 4-4 4 4"/></svg>`}
function renderPieces(lev){const layer=document.getElementById('pieceLayer');layer.innerHTML='';positions.forEach((pos,i)=>{if(!pos)return;const p=lev.pieces[i],el=document.createElement('button');el.className=`latchling expr-${expressionFor(currentLevel,i,p)} ${i===selected?'selected':''}`;el.dataset.pi=i;el.style.setProperty('--n',lev.size);el.style.setProperty('--piece-color',COLORS[p.color]);el.style.setProperty('--light',LIGHT[p.color]);el.style.setProperty('--dark',DARK[p.color]);placePiece(el,pos[0],pos[1],lev.size,false);el.innerHTML=`<span class="suit-mark">${suitSvg(p.suit)}</span><span class="face"><span class="eyes"><i class="eye"></i><i class="eye"></i></span><i class="mouth"></i></span>`;el.onclick=()=>{if(animating)return;selected=i;renderPieces(lev)};layer.appendChild(el)})}
function placePiece(el,r,c,n,animate=false){el.style.left=`${c*100/n}%`;el.style.top=`${r*100/n}%`}
