'use strict';
const assert=require('node:assert/strict'),path=require('node:path');
const {loadCampaign}=require('../tools/campaign/runtime.cjs'),{candidate}=require('../tools/campaign/candidates.cjs'),{reviewLevel}=require('../tools/campaign/review.cjs');
const {anchorDependencies,anchorFailures}=require('../tools/campaign/anchor-review.cjs');
const {levels,simulateState}=loadCampaign(path.resolve(__dirname,'..'));
const a=candidate({size:5,pieces:2,rocks:4,anchors:2,geometry:'corners'},7643,101);
assert.equal(a.anchors.length,2,'offline construction must place the requested anchor stops');
const occupied=[...a.pieces.map(p=>p.pos),...a.nests,...a.rocks,...a.anchors].map(p=>p.join(','));assert.equal(new Set(occupied).size,occupied.length,'stops may not hide beneath residents, nests or rocks');
assert.deepEqual(a,candidate({size:5,pieces:2,rocks:4,anchors:2,geometry:'corners'},7643,101));
const exact=JSON.parse(JSON.stringify(levels[0]));Object.assign(exact,{id:101,chapter:3,nests:[[2,3]],rocks:[],anchors:[[2,0]],solution:[[0,'D'],[0,'R']],optimal:2,moveLimit:4});exact.pieces[0].pos=[0,0];
const evidence=reviewLevel(exact,simulateState,{focus:['anchors']});
assert.equal(evidence.proof.status,'solved');assert.equal(evidence.proof.optimum,2);assert(evidence.comparisons.authoredSolved);
assert(evidence.witnesses.some(w=>w.mechanic==='anchors'&&w.effect==='intended-trajectory'));
assert.equal(evidence.comparisons.removal.anchors,false,'exact anchor stop must change the intended route, not decorate it');
assert.deepEqual(anchorFailures(exact,simulateState),[],'focused introduction need not invent helper complexity');
const frozen=loadCampaign(path.resolve(__dirname,'..'),{revision:'c79f39f'}).levels;
const parked=anchorDependencies(frozen[109],simulateState);
assert(parked.connections.some(w=>w.type==='parked-helper'),'an anchor must place a helper before it can certify a parked-helper connection');
assert(parked.connections.some(w=>w.type==='anchor-launch'),'exact launch can connect an anchor to the next helper stop');
assert.equal(anchorDependencies({...frozen[109],anchors:[]},simulateState).connections.length,0);
assert(anchorFailures({...frozen[103],id:116},simulateState).some(e=>/connection|Disconnected/.test(e)),'independent anchor errands do not certify a combination board');
console.log('PASS deterministic exclusive anchor construction and real-engine exact-stop evidence');
